In [1]:
import pandas as pd

In [43]:
path = "/home/mpac/Projetos/Curica/curica_streamlit_censo/data/fnde/fundeb.csv"

df_fundeb = pd.read_csv(path, sep=';', encoding='latin', low_memory=False)

In [44]:
df_fundeb.head(5)

,COD_MUN,Município,UF,Município - UF,Mês,2007,2008,2009,2010,2011,...,2019,2020,2021,2022,2023,2024,2025,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,643.0,Acrelândia,AC,Acrelândia - AC,1.0,"271.775,97","450.935,06","484.772,76","407.833,04","597.904,87",...,"861.747,15","793.048,36","1.018.924,46","1.331.855,45","1.787.408,13","1.815.350,44","1.926.974,37",NaN,NaN,NaN
1,643.0,Acrelândia,AC,Acrelândia - AC,2.0,"280.869,80","458.391,25","458.508,64","471.105,76","639.142,00",...,"900.609,50","1.088.733,79","1.251.773,07","1.688.744,81","1.705.678,35","1.954.245,70","2.065.052,75",NaN,NaN,NaN
2,643.0,Acrelândia,AC,Acrelândia - AC,3.0,"267.766,24","373.189,77","402.307,75","399.129,32","476.030,76",...,"711.703,16","728.413,51","915.759,93","1.232.619,86","1.188.223,24","1.388.337,85","1.505.402,50",NaN,NaN,NaN
3,643.0,Acrelândia,AC,Acrelândia - AC,4.0,"380.866,48","443.127,06","398.573,19","453.902,42","565.926,97",...,"718.405,94","676.049,56","896.060,63","1.371.651,07","1.287.441,19","1.467.411,49",-,NaN,NaN,NaN
4,643.0,Acrelândia,AC,Acrelândia - AC,5.0,"321.605,33","448.585,10","485.830,60","549.101,90","626.097,21",...,"825.357,96","669.344,71","973.985,75","1.541.240,29","1.411.334,28","1.585.567,54",-,NaN,NaN,NaN

In [45]:
df_fundeb.shape

(66843, 27)

In [55]:
df_fundeb_ac = df_fundeb[(df_fundeb['UF'] == 'AC')]

df_fundeb_ac.shape

(264, 27)

In [56]:
for idx, coluna in enumerate(df_fundeb_ac):
    print(f"{idx}: {coluna}")

0: COD_MUN
1: Município
2: UF
3: Município - UF
4: Mês
5: 2007
6: 2008
7: 2009
8: 2010
9: 2011
10: 2012
11: 2013
12: 2014
13: 2015
14: 2016
15: 2017
16: 2018
17: 2019
18: 2020
19: 2021
20: 2022
21: 2023
22: 2024
23: 2025
24: Unnamed: 24
25: Unnamed: 25
26: Unnamed: 26

In [57]:
df_fundeb_ac = df_fundeb_ac.drop(columns=df_fundeb_ac.columns[[0, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 23, 24, 25, 26]])

In [58]:
df_fundeb_ac.shape

(264, 9)

In [59]:
for idx, coluna in enumerate(df_fundeb_ac):
    print(f"{idx}: {coluna}")

0: Município
1: UF
2: Mês
3: 2019
4: 2020
5: 2021
6: 2022
7: 2023
8: 2024

In [60]:
df_fundeb_ac.head(12)

,Município,UF,Mês,2019,2020,2021,2022,2023,2024
0,Acrelândia,AC,1.0,"861.747,15","793.048,36","1.018.924,46","1.331.855,45","1.787.408,13","1.815.350,44"
1,Acrelândia,AC,2.0,"900.609,50","1.088.733,79","1.251.773,07","1.688.744,81","1.705.678,35","1.954.245,70"
2,Acrelândia,AC,3.0,"711.703,16","728.413,51","915.759,93","1.232.619,86","1.188.223,24","1.388.337,85"
3,Acrelândia,AC,4.0,"718.405,94","676.049,56","896.060,63","1.371.651,07","1.287.441,19","1.467.411,49"
4,Acrelândia,AC,5.0,"825.357,96","669.344,71","973.985,75","1.541.240,29","1.411.334,28","1.585.567,54"
5,Acrelândia,AC,6.0,"676.517,09","599.104,52","961.452,10","1.435.004,13","1.359.232,19","1.707.396,01"
6,Acrelândia,AC,7.0,"760.446,15","622.854,38","841.404,83","1.326.076,66","1.142.060,13","1.290.650,37"
7,Acrelândia,AC,8.0,"696.022,61","691.272,91","1.063.936,77","1.448.463,84","1.270.745,13","1.567.122,46"
8,Acrelândia,AC,9.0,"667.612,52","619.358,57","856.668,41","1.288.677,12","1.158.126,80","1.379.138,49"
9,Acrelândia,AC,10.0,"651.903,12","753.833,73","951.690,79","1.315.111,43","1.237.307,91","1.456.163,65"
10,Acrelândia,AC,11.0,"757.361,32","938.187,15","1.160.675,91","1.546.111,88","1.423.483,27","1.725.272,68"
11,Acrelândia,AC,12.0,"969.389,31","982.196,99","1.223.295,59","1.637.030,94","1.579.982,16","1.965.384,82"

In [61]:
import pandas as pd
import os

# 1. Leitura correta do CSV, com separador ponto-e-vírgula
#df_fundeb_ac = pd.read_csv('data/fundeb/df_fundeb_original.csv', sep=';', encoding='utf-8', low_memory=False)

# 2. Corrigir as colunas de valores numéricos
colunas_valores = ['2019', '2020', '2021', '2022', '2023', '2024']

for coluna in colunas_valores:
    df_fundeb_ac[coluna] = (
        df_fundeb_ac[coluna]
        .astype(str)
        .str.replace('.', '', regex=False)     # remove separador de milhar
        .str.replace(',', '.', regex=False)     # troca vírgula decimal por ponto
        .str.strip()                             # remove espaços extras
        .astype(float)
    )

# 3. Agrupar por Município
df_fundeb_ac = (
    df_fundeb_ac
    .groupby('Município')[colunas_valores]
    .sum()
    .reset_index()
)

# 4. Salvar CSV com valores convertidos
# os.makedirs('data/fundeb', exist_ok=True)
# df_fundeb_ac.to_csv('data/fundeb/df_fundeb_ac.csv', sep=';', index=False, encoding='utf-8', float_format="%.2f")

# print("CSV salvo com sucesso.")

df_fundeb_ac.head(5)

,Município,2019,2020,2021,2022,2023,2024
0,Acrelândia,9197075.83,9162398.18,12115628.24,17162587.48,16551022.78,19302041.50
1,Assis Brasil,6156020.20,6262285.54,8329734.83,9705020.49,10237145.04,12788411.12
2,Brasiléia,12368416.39,12854851.62,18940150.41,24783988.44,26859192.37,30589023.28
3,Bujari,6838251.76,7273835.30,9456004.80,11732871.28,10831495.78,14221704.00
4,Capixaba,8498777.29,8269874.43,12239089.08,18628858.89,19467400.34,18098142.56

In [ ]:
# Convertendo df_fundeb_ac para formato longo
df_fundeb_ac_longo = df_fundeb_ac.melt(
    id_vars=['Município'],        # Mantém Município fixo
    value_vars=['2019', '2020', '2021', '2022', '2023', '2024'],  # Colunas que queremos "derreter"
    var_name='Ano',               # Nome da nova coluna para os anos
    value_name='Total_Repassado'  # Nome da nova coluna para os valores somados
)

# Exibir o resultado
df_fundeb_ac_longo.head(5)

      Município   Ano  Total_Repassado
0    Acrelândia  2019       9197075.83
1  Assis Brasil  2019       6156020.20
2     Brasiléia  2019      12368416.39
3        Bujari  2019       6838251.76
4      Capixaba  2019       8498777.29

In [63]:
# 4. Salvar CSV com valores convertidos
os.makedirs('data/fundeb', exist_ok=True)
df_fundeb_ac.to_csv('data/fundeb/df_fundeb_ac.csv', sep=';', index=False, encoding='utf-8', float_format="%.2f")

print("CSV salvo com sucesso.")

CSV salvo com sucesso.